const movies = [
  {
    id: 1,
    title: "Spider-Man: No Way Home",
    vote_average: 8.2,
    release_date: "2021-12-17",
    runtime: 148,
    genres: "Action, Adventure",
    overview: "For the first time in the cinematic history of Spider-Man, our hero is unmasked and can no longer separate his normal life from the high-stakes of being a Super Hero.",
    poster_path: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
  }, 
  {
    id: 2,
    title: "Avengers: Infinity War",
    vote_average: 8.4,
    release_date: "2018-04-27",
    runtime: 149,
    genres: "Action, Sci-Fi",
    overview: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.",
    poster_path: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
  },
  {
    id: 3,
    title: "Inception",
    vote_average: 8.8,
    release_date: "2010-07-16",
    runtime: 148,
    genres: "Action, Sci-Fi",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster_path: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
  },
  {
    id: 4,
    title: "Interstellar",
    vote_average: 8.6,
    release_date: "2014-11-05",
    runtime: 169,
    genres: "Adventure, Drama, Sci-Fi",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster_path: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
  },
  {
    id: 5,
    title: "The Dark Knight",
    vote_average: 9.0,
    release_date: "2008-07-18",
    runtime: 152,
    genres: "Action, Crime, Drama",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster_path: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CejMDZkl.jpg",
  },
  {
    id: 6,
    title: "Aquaman",
    vote_average: 6.9,
    release_date: "2018-12-21",
    runtime: 143,
    genres: "Action, Adventure, Fantasy",
    overview: "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
    poster_path: "https://image.tmdb.org/t/p/w500/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/9lJ9aikvADsAbNxpKi1tCGCXFsL.jpg",
  },
];

export default movies;